allowBuilds:
  '@reown/appkit': true
  bigint-buffer: true
  bufferutil: true
  core-js: true
  esbuild: true
  keccak: true
  secp256k1: true
  sharp: false
  unrs-resolver: false
  utf-8-validate: false
  workerd: true
