allowBuilds:
  '@reown/appkit': true
  bigint-buffer: true
  bufferutil: true
  core-js: set this to true or false
  keccak: true
  secp256k1: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
